# Generated by Django 4.2.5 on 2023-12-11 15:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('IBT', '0002_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
