# Generated by Django 4.2.5 on 2023-09-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='images2/')),
            ],
        ),
    ]
